{% set name = "torchfile" %}
{% set version = "0.1.0" %}
{% set hash = "a53dfe134b737845a9f2cb24fe0585317874f965932cebdb0439d13c8da4136e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - torchfile

about:
  home: https://github.com/bshillingford/python-torchfile
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Deserialize torch-serialized objects from Python.
  description: |
    Mostly direct port of the torch7 Lua and C serialization implementation to
    Python, depending only on numpy (and the standard library: array and
    struct). Sharing of objects including torch.Tensors is preserved.
  dev_url: https://github.com/bshillingford/python-torchfile

extra:
  recipe-maintainers:
    - andfoy
    - synapticarbors
