travis:
  secure:
    BINSTAR_TOKEN: QBvZcIibrp5Vj4flbDpE7hqLsxKiaMnZUyBWawc1gZv00h8RrN/EUvFfA+1iaSjHtNtR3m7gFGFrJhWo6vUC2gyPGX98OuyFNfsqwJMnsYM4dtwFLgitglrtHIhJmzbcrk61+0Qpabxh1kwAyEdfvq1XeLsN5GfJnFp/NRr2lWeguwAmzcYXbu3b0X9UeCeXzz5qwEtKbHdZ5GW/uEwyBTEV7ARaJ1olryQruZXuyy0QdM8am8BYhRslsJtYT9sZs8l3WJFg7BYmwiQjs5B9ir7kV/eaP+GiMtmxCi2zwxHx+F2qj7X3cNqKkGaGdS62Wj39Mjkohlyx8g99bXoZEQvZvGN3CoikWtCy17V97MvgpXhvDvm+t21gnJjr4+WuMzVWJIo48Qjl1JGxztorngQbczcJMd95ryXBmaGuPmGl4Cs8tZwbJq0OHthUWYYUw0J1daMwKxUx0cbp75Vhp0zh+53Lo5oErv6MqbRWbjmDYIC4SylzU1RzFazGxgHmTdBoyjPm4PREJmXwPrH8od4jgHkeeJJHUqtU4x/wESHNzDNo5qwlQXm3e+5fYOr+RyaWdB+Sj0C2633fDuCTN1H8UMQ0GvWTE01YrPS0GBUjz6GmycM9qvNR/37zoRDvZAoDE/sd26VRL7UF9laIGK/v5AsJ+MwP20U7BHvFSSU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
