travis:
  secure:
    BINSTAR_TOKEN: XUI4Rnenkc4v3bQb4XEkyrYAafCD2rs/Io5khm1+OlkPFLIKjBu+9gsfv+/j311hCD+xH4qvZc3WfCFkITsvQuuMektBlium/PMi6mIvSXruUr2HzU2q07KYedeYc1/nO8O8T5QGcDKiQxQQ/49xMsjlK42UtnNSY0l+Jw4MkrewnxxDu5lkFzkTDjU/Ac+sqhmVS7T5cbZehiZs1KYFGf25/h1ZNTEVD3CXYiA0oyXAnIvKKMRrI3kq0kZkVm3zAPTsQUx7WhnuYoveP6cxTex4LsRkmHTimhPVyn7YwvbnvUCBFlQOtSp2/n7hGawtohvHsvgols0LzBoccM/UVYpMATp3WZys2nREUpB1rnk696xkwTUEElZ36Yl0QJ9ouFsGi0XZJNBhI4Bl5sH5TR2dpRPqBBfzvhV8/wVayN9bC/mUJdzNkmxh4vejFmcsOM96Q+nE3k7qVDU9zaMSacdEPi5fbGDNmKFKrpV7tWoQrZybfKLhsXPL9z3krAvc4in2QYTrcmFmWcFQ7WODem4auFZaqMuuI44MCHBdTSoO723KmWaHiwRxsrrqbbHF0jVNa3IZhQ2QLWW8sfPu/nxETTIKZJdgbU6CtqwyLzXZM95z2xlhBWeT1LWcIiVHQzlOmzhYIULC5ozt2JJLZxaO8UmeMP/M9uxT7y53JSA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
